services:
  kombi-analytics:
    build: .
    container_name: telemetry-analytics
    restart: always
    networks:
      - kombi-network
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis-msg-center
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - WS_CORE_URL=ws://telemetry-core:3000
      - WS_PORT=3001
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 128M

networks:
  kombi-network:
    external: true